# Generated by Django 6.0.7 on 2026-07-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='summa',
            field=models.PositiveIntegerField(),
        ),
    ]
