# Generated by Django 6.0.7 on 2026-07-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarf', '0002_alter_expense_summa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='xarajat_sanasi',
            field=models.DateField(),
        ),
    ]
