# Generated by Django 6.0.7 on 2026-07-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarf', '0003_alter_expense_xarajat_sanasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='xarajat_sanasi',
            field=models.DateTimeField(),
        ),
    ]
